### ISSUE TITLE
Can not add new form in final testing

### ISSUE THREAD

**Issue by MohamedEshmawy** [mohamedatef98/SE2018G29#1]

**Comment by MohamedEshmawy** [comment]
ERROR:::


{"headers":{"normalizedNames":{},"lazyUpdate":null},"status":401,"statusText":"Unauthorized","url":"http://prototype-forms.herokuapp.com/api/forms?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9wcm90b3R5cGUtZm9ybXMuaGVyb2t1YXBwLmNvbVwvYXBpXC9sb2dpbiIsImlhdCI6MTU1MDE5MzMyNCwiZXhwIjoxNTUwMTk2OTI0LCJuYmYiOjE1NTAxOTMzMjQsImp0aSI6IjRpRzh6ckRkVGdORWJhTHciLCJzdWIiOjMsInBydiI6Ijg3ZTBhZjFlZjlmZDE1ODEyZmRlYzk3MTUzYTE0ZTBiMDQ3NTQ2YWEifQ.FzvD_GkFZivVAE0gqv9i3qoeedNGPOjzfd5_Nir2mZ0","ok":false,"name":"HttpErrorResponse","message":"Http failure response for http://prototype-forms.herokuapp.com/api/forms?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9wcm90b3R5cGUtZm9ybXMuaGVyb2t1YXBwLmNvbVwvYXBpXC9sb2dpbiIsImlhdCI6MTU1MDE5MzMyNCwiZXhwIjoxNTUwMTk2OTI0LCJuYmYiOjE1NTAxOTMzMjQsImp0aSI6IjRpRzh6ckRkVGdORWJhTHciLCJzdWIiOjMsInBydiI6Ijg3ZTBhZjFlZjlmZDE1ODEyZmRlYzk3MTUzYTE0ZTBiMDQ3NTQ2YWEifQ.FzvD_GkFZivVAE0gqv9i3qoeedNGPOjzfd5_Nir2mZ0: 401 Unauthorized","error":{"message":"Token has expired","exception":"Symfony\\Component\\HttpKernel\\Exception\\UnauthorizedHttpException","file":"/app/vendor/tymon/jwt-auth/src/Http/Middleware/BaseMiddleware.php","line":74,"trace":[{"file":"/app/vendor/tymon/jwt-auth/src/Http/Middleware/Authenticate.php","line":30,"function":"authenticate","class":"Tymon\\JWTAuth\\Http\\Middleware\\BaseMiddleware","type":"->"},{"file":"/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":163,"function":"handle","class":"Tymon\\JWTAuth\\Http\\Middleware\\Authenticate","type":"->"},{"file":"/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php","line":53,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/app/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php","line":41,"function":"Illuminate\\Routing\\{closure}","class":"Illuminate\\Routing\\Pipeline","type":"->"},{"file":"/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":163,"function":"handle","class":"Illuminate\\Routing\\Middleware\\SubstituteBindings","type":"->"},{"file":"/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php","line":53,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/app/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php","line":58,"function":"Illuminate\\Routing\\{closure}","class":"Illuminate\\Routing\\Pipeline","type":"->"},{"file":"/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":163,"function":"handle","class":"Illuminate\\Routing\\Middleware\\ThrottleRequests","type":"->"},{"file":"/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php","line":53,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":104,"function":"Illuminate\\Routing\\{closure}","class":"Illuminate\\Routing\\Pipeline","type":"->"},{"file":"/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php","line":684,"function":"then","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php","line":659,"function":"runRouteWithinStack","class":"Illuminate\\Routing\\Router","type":"->"},{"file":"/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php","line":625,"function":"runRoute","class":"Illuminate\\Routing\\Router","type":"->"},{"file":"/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php","line":614,"function":"dispatchToRoute","class":"Illuminate\\Routing\\Router","type":"->"},{"file":"/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php","line":176,"function":"dispatch","class":"Illuminate\\Routing\\Router","type":"->"},{"file":"/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php","line":30,"function":"Illuminate\\Foundation\\Http\\{closure}","class":"Illuminate\\Foundation\\Http\\Kernel","type":"->"},{"file":"/app/vendor/fideloper/proxy/src/TrustProxies.php","line":57,"function":"Illuminate\\Routing\\{closure}","class":"Illuminate\\Routing\\Pipeline","type":"->"},{"file":"/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":163,"function":"handle","class":"Fideloper\\Proxy\\TrustProxies","type":"->"},{"file":"/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php","line":53,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php","line":31,"function":"Illuminate\\Routing\\{closure}","class":"Illuminate\\Routing\\Pipeline","type":"->"},{"file":"/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":163,"function":"handle","class":"Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest","type":"->"},{"file":"/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php","line":53,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php","line":31,"function":"Illuminate\\Routing\\{closure}","class":"Illuminate\\Routing\\Pipeline","type":"->"},{"file":"/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":163,"function":"handle","class":"Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest","type":"->"},{"file":"/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php","line":53,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php","line":27,"function":"Illuminate\\Routing\\{closure}","class":"Illuminate\\Routing\\Pipeline","type":"->"},{"file":"/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":163,"function":"handle","class":"Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize","type":"->"},{"file":"/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php","line":53,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php","line":62,"function":"Illuminate\\Routing\\{closure}","class":"Illuminate\\Routing\\Pipeline","type":"->"},{"file":"/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":163,"function":"handle","class":"Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode","type":"->"},{"file":"/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php","line":53,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":104,"function":"Illuminate\\Routing\\{closure}","class":"Illuminate\\Routing\\Pipeline","type":"->"},{"file":"/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php","line":151,"function":"then","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php","line":116,"function":"sendRequestThroughRouter","class":"Illuminate\\Foundation\\Http\\Kernel","type":"->"},{"file":"/app/public/index.php","line":59,"function":"handle","class":"Illuminate\\Foundation\\Http\\Kernel","type":"->"}]}}

**Comment by mohamedatef98** [comment]
Fixed by increase token expiration period
1f0920285f8dbff29b7f8aa41f0a8434d7d5458c
